---
- name: Install learners in virtualenv
  become: true
  become_user: "{{ learners_user }}"
  ansible.builtin.pip:
    name: "{{ learners_basepath }}"
    virtualenv: "{{ learners_basepath }}/venv"
    virtualenv_command: python3.9 -m venv

- name: Write config
  become: true
  ansible.builtin.template:
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    src: templates/config.yml.j2
    dest: "{{ learners_basepath }}/config.yml"
    mode: preserve

- name: Create uploads folder {{ learners_config_learners.upload_folder }}
  become: true
  ansible.builtin.file:
    path: "{{ learners_config_learners.upload_folder }}"
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    mode: "0755"
    state: directory
  when: learners_config_learners.upload_folder is defined

- name: Create www_root {{ learners_wwwroot }}
  become: true
  ansible.builtin.file:
    path: "{{ learners_wwwroot }}"
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    mode: "0755"
    state: directory
