---
- name: Copy CSS
  become: true
  ansible.builtin.copy:
    src: "{{ learners_branding_basepath | default(omit) }}theme.scss"
    dest: "{{ learners_install_path }}/static/css/theme_{{ learners_config_learners.theme }}.scss"
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    mode: preserve
  when:
    - learners_branding.scss | default(False)
    - learners_config_learners is defined

- name: Replace Logo
  become: true
  ansible.builtin.copy:
    src: "{{ learners_branding_basepath | default(omit) }}logo.html"
    dest: "{{ learners_install_path }}/templates/partials/logo.html"
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    mode: preserve
  when: learners_branding.logo | default(False)

- name: Replace Login
  become: true
  ansible.builtin.copy:
    src: "{{ learners_branding_basepath | default(omit) }}login.html"
    dest: "{{ learners_install_path }}/templates/login.html"
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    mode: preserve
  when: learners_branding.login | default(False)
