---

- name: "Create documentation/exercises base config file"
  ansible.builtin.template:
    src: hugo_config.yaml.j2
    dest: "{{ learners_exercises_paths.config }}/{{ item.key }}_config.yaml"
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    mode: 0644
  become: true
  loop: "{{ hugo_vars['general'] | dict2items }}"

- name: Deploy EXERCISES files per user
  include_tasks: ./configure_hugo.yml
  vars:
    username: "{{ user_files.key }}"
    params: "{{ user_files.value['exercises']['params'] }}"
    type: "exercises"
    general: "{{ hugo_vars['general']['exercises'] }}"
  loop: "{{ hugo_vars['users'] | dict2items }}"
  loop_control:
    loop_var: user_files

- name: Deploy DOCUMENTATION files per user
  include_tasks: ./configure_hugo.yml
  vars:
    username: "{{ user_files.key }}"
    params: "{{ user_files.value['documentation']['params'] }}"
    type: "documentation"
    general: "{{ hugo_vars['general']['documentation'] }}"
  loop: "{{ hugo_vars['users'] | dict2items }}"
  loop_control:
    loop_var: user_files
