---
- name: Ensure learners build packages are installed
  ansible.builtin.package:
    name: "{{ learners_packages }}"
    state: present
    update_cache: true
  become: true

- name: Cleanup base directory for reinstall
  ansible.builtin.file:
    path: "{{ learners_exercises_paths.base }}"
    state: absent
  when: learners_exercises_git.learners_exercises['always_reinstall']
  become: true

- name: Ensure exercises paths exist
  ansible.builtin.file:
    path: "{{ learners_exercises_paths.base }}"
    owner: "{{ learners_user }}"
    group: "{{ learners_usergroup }}"
    state: directory
    mode: 0755
  become: true


- name: Ensure config paths exist
  ansible.builtin.file:
    path: "{{ learners_exercises_paths.config }}"
    owner: "{{ learners_user }}"
    group: "{{ learners_usergroup }}"
    state: directory
    mode: 0640
  become: true

- name: "Create documentation/exercises base config file"
  ansible.builtin.template:
    src: hugo_config.yaml.j2
    dest: "{{ learners_exercises_paths.config }}/{{ item.key }}_config.yaml"
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    mode: 0644
  become: true
  loop: "{{ hugo_vars['general'] | dict2items }}"

- name: Deploy EXERCISES files per user
  include_tasks: ./configure_hugo.yml
  vars:
    username: "{{ user_files.key }}"
    params: "{{ user_files.value['exercises']['params'] }}"
    type: "exercises"
    general: "{{ hugo_vars['general']['exercises'] }}"
  loop: "{{ hugo_vars['users'] | dict2items }}"
  loop_control:
    loop_var: user_files

- name: Deploy DOCUMENTATION files per user
  include_tasks: ./configure_hugo.yml
  vars:
    username: "{{ user_files.key }}"
    params: "{{ user_files.value['documentation']['params'] }}"
    type: "documentation"
    general: "{{ hugo_vars['general']['documentation'] }}"
  loop: "{{ hugo_vars['users'] | dict2items }}"
  loop_control:
    loop_var: user_files

- name: "Remove default config"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/conf.d"
  become: true
  notify: restart nginx

- name: Add NGINX configuration file
  ansible.builtin.template:
    src: nginx_learners.conf.j2
    dest: /etc/nginx/sites-enabled/learners.conf
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    mode: 0644
  become: true
  notify: restart nginx
