---
- name: Check github pat
  debug:
    msg: "GITHUB PAT ist unset please set `learners_github_pat`"
  when: learners_github_pat == ""

- name: Clone Exercise to {{ learners_exercise_build_path }}
  ansible.builtin.git:
    repo: "{{ learners_exercise_repository }}"
    dest: "{{ learners_exercise_build_path }}"
    version: "{{ learners_exercise_branch }}"
    accept_hostkey: true
    single_branch: true
    recursive: false
    force: true
    depth: 1
  become: true
  become_user: "{{ learners_user }}"
  environment:
    GIT_TERMINAL_PROMPT: "0"

- name: Clone Theme to {{ learners_exercise_build_path }}/themes/learners/
  ansible.builtin.git:
    repo: "{{ learners_theme_repository }}"
    dest: "{{ learners_exercise_build_path }}/themes/learners/"
    version: "{{ learners_theme_branch }}"
    accept_hostkey: true
    single_branch: true
    force: true
    depth: 1
  become: true
  become_user: "{{ learners_user }}"
  environment:
    GIT_TERMINAL_PROMPT: "0"

- name: Render exercise & documentation with hugo
  include_tasks: render_hugo.yml
  loop: "{{ learners_exercise_params }}"
