---
- name: Clone Exercise to {{ learners_exercise_build_path }}
  ansible.builtin.git:
    repo: "{{ learners_exercise_repository }}"
    dest: "{{ learners_exercise_build_path }}"
    version: "{{ learners_exercise_branch }}"
    accept_hostkey: true
    single_branch: true
    recursive: false
    force: true
    depth: 1
  become: true
  become_user: "{{ learners_user }}"

- name: Clone Theme to {{ learners_exercise_build_path }}/themes/learners/
  ansible.builtin.git:
    repo: "{{ learners_theme_repository }}"
    dest: "{{ learners_exercise_build_path }}/themes/learners/"
    version: "{{ learners_theme_branch }}"
    accept_hostkey: true
    single_branch: true
    force: true
    depth: 1
  become: true
  become_user: "{{ learners_user }}"

- name: Render exercise & documentation with hugo
  include_tasks: render_hugo.yml
  loop: "{{ learners_exercise_params }}"
  notify: restart learners
