---
- name: Clone Learners to {{ learners_basepath }}
  become: true
  become_user: "{{ learners_user }}"
  ansible.builtin.git:
    repo: https://{{ learners_github_pat }}@github.com/ait-cs-IaaS/learners.git
    dest: "{{ learners_basepath }}"
    version: "{{ learners_backend_branch }}"
    accept_hostkey: true
    single_branch: true
    recursive: false
    force: true
    depth: 1
  environment:
    GIT_TERMINAL_PROMPT: "0"

- name: Write config
  become: true
  ansible.builtin.template:
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    src: templates/config.yml.j2
    dest: "{{ learners_basepath }}/config.yml"
    mode: preserve

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Get Nodejs version
  ansible.builtin.set_fact:
    node_version: "{{ (ansible_facts.packages['nodejs'][0]['version'].split('.')[:2] | join('.')) | default('0.0') }}"
  when: "'nodejs' in ansible_facts.packages"

- name: Install Nodejs 19.x
  when: ((node_version | default('0.0')) | float) < 19.0
  become: true
  block:
    - name: Download node setup file
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_19.x
        dest: /tmp/setup_19.sh
        owner: "{{ learners_user }}"
        group: "{{ learners_user }}"
        mode: a+x

    - name: Execute bash script
      ansible.builtin.command:
        cmd: /tmp/setup_19.sh
      changed_when: false

    - name: Install node 19.x via apt
      ansible.builtin.apt:
        name: nodejs

    - name: Remove temporary file
      ansible.builtin.file:
        path: /tmp/setup_19.sh
        state: absent

- name: Install yarn
  become: true
  community.general.npm:
    name: yarn
    global: true

- name: Install dependencies
  become: true
  become_user: "{{ learners_user }}"
  ansible.builtin.command:
    cmd: yarn install
    chdir: "{{ learners_basepath }}/frontend"
  changed_when: false

- name: Set .env for frontend
  become: true
  ansible.builtin.template:
    src: env.j2
    dest: "{{ learners_basepath }}/frontend/.env"
    mode: "0644"
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"

- name: Build project
  become: true
  become_user: "{{ learners_user }}"
  ansible.builtin.command:
    cmd: yarn build
    chdir: "{{ learners_basepath }}/frontend"
  changed_when: false

- name: Copy build to live directory
  become: true
  ansible.builtin.copy:
    src: "{{ learners_basepath }}/frontend/dist/"
    dest: /var/www/html/learners
    mode: "755"
    remote_src: true

- name: Add NGINX configuration file
  become: true
  ansible.builtin.template:
    src: nginx_learners.conf.j2
    dest: /etc/nginx/conf.d/learners.conf
    mode: "0644"
  notify: Restart nginx
