---
- name: Ensure learners build packages are installed
  become: true
  ansible.builtin.package:
    name: "{{ learners_packages }}"
    state: present
    update_cache: true

- name: Create learners user
  become: true
  ansible.builtin.user:
    name: "{{ learners_user }}"
    home: "{{ learners_basepath }}"
    shell: /usr/sbin/nologin
    create_home: false

- name: Create {{ learners_basepath }}
  become: true
  ansible.builtin.file:
    path: "{{ learners_basepath }}"
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    mode: 0755
    state: directory

- name: Copying service-template to server
  become: true
  ansible.builtin.template:
    src: templates/learners.service.j2
    dest: /etc/systemd/system/learners.service
    mode: preserve

- name: Install learners in virtualenv
  become: true
  become_user: "{{ learners_user }}"
  ansible.builtin.pip:
    name: https://github.com/ait-cs-IaaS/learners/releases/download/{{ learners_pip_version }}/ait-learners-{{ learners_pip_version }}.tar.gz
    virtualenv: "{{ learners_basepath }}/venv"
    virtualenv_command: python3 -m venv

- name: Write config
  become: true
  ansible.builtin.template:
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    src: templates/config.yml.j2
    dest: "{{ learners_basepath }}/config.yml"
    mode: preserve
  notify: Restart learners

- name: Start learners service
  ansible.builtin.systemd:
    name: learners.service
    state: started
    enabled: true
    daemon_reload: true
  become: true
