---
- name: Copying service-template to server
  become: true
  ansible.builtin.template:
    src: templates/learners.service.j2
    dest: /etc/systemd/system/learners.service
    mode: preserve

- name: Install build modules
  become: true
  become_user: "{{ learners_user }}"
  ansible.builtin.pip:
    name: [setuptools, wheel, build]

- name: Install learners in virtualenv
  become: true
  become_user: "{{ learners_user }}"
  ansible.builtin.pip:
    name: "https://github.com/ait-cs-IaaS/learners/archive/refs/heads/{{ learners_backend_branch }}.zip"
    virtualenv: "{{ learners_basepath }}/venv"
    virtualenv_command: python3.9 -m venv

- name: Check Subdirectories existence
  ansible.builtin.stat:
    path: "{{ learners_wwwroot }}/hugo/base/en/{{ item }}"
  register: dir_check
  loop: "{{ learners_default_content }}"

- name: Create tabs default object
  ansible.builtin.set_fact:
    content_present_in_repo: "{{ content_present_in_repo | default({}) | combine({item.item: item.stat.exists}) }}"
  loop: "{{ dir_check.results }}"

- name: Create uploads folder {{ learners_config_learners.upload_folder }}
  become: true
  ansible.builtin.file:
    path: "{{ learners_config_learners.upload_folder }}"
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    mode: "0755"
    state: directory
  when: learners_config_learners.upload_folder is defined

- name: Start learners service
  ansible.builtin.systemd:
    name: learners.service
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
