---
- name: Deploy mattermost Server
  import_role:
    name: "ansible-mattermost"
    when: learners_deploy_mattermost
    # vars_from: "/{{ role_path }}/vars/learners.yml"


- name: Deploy learners App
  import_role:
    name: "ansible-flask"
    vars_from: "/{{ role_path }}/vars/learners.yml"


- name: Deploy venjix
  import_role:
    name: "ansible-flask"
    vars_from: "/{{ role_path }}/vars/venjix.yml"

- include_tasks: exercises.yml
  tags: [exercises]
