---
- name: Load default vars
  ansible.builtin.include_vars: learners.yml

- name: Install learners
  ansible.builtin.include_tasks: learners.yml
  tags: [learners]
- name: Learners branding
  ansible.builtin.include_tasks: branding.yml
  tags: [learners, branding]
- name: Configure exercises
  ansible.builtin.include_tasks: exercises.yml
  tags: [exercises]
  when: (learners_deploy.full | default(False) ) or 
        (learners_deploy.documentation | default(False) ) or 
        (learners_deploy.exercises | default(False) ) or 
        (learners_deploy.presentations | default(False) )

- name: Configure nginx
  ansible.builtin.include_tasks: nginx.yml
  tags: [nginx]
