---

# -------------------------------------------
# *** Prerequisites ***
# -------------------------------------------

- name: Set github access token
  pause:
    prompt: "Please enter the github access token"
    echo: yes
  register: access_token
  when: not LEARNERS_ACCESS_TOKEN

- name: Register Access Token
  set_fact:
    LEARNERS_ACCESS_TOKEN: "{{ access_token.user_input  }}"
  when: access_token.user_input is defined


- name: Adding "{{ learners_user }}" user
  ansible.builtin.user:
    name: "{{ learners_user }}"
    group: "{{ learners_usergroup }}"
    shell: /bin/bash
    password: "{{ learners_user_password | password_hash('sha512') }}"
    generate_ssh_key: yes
  become: yes


- name: Ensure <{{ learners_base_packages | join(', ') }}> is installed
  ansible.builtin.package:
    name: "{{ learners_base_packages }}"
    state: latest
    update_cache: yes
  become: yes

- name: Cleanup base directory for reinstall
  ansible.builtin.file:
    path: "{{ learners_paths.base }}"
    state: absent
  become: yes
  when: learners_git.always_reinstall

- name: Ensure learners paths exist
  ansible.builtin.file:
    path: "{{ item.value }}"
    owner: "{{ learners_user }}"
    group: "{{ learners_usergroup }}"
    state: directory
  become: yes
  loop: "{{ learners_paths | dict2items }}"

# -------------------------------------------
# *** Exercises ***
# -------------------------------------------

- include: exercises.yml
  tags: [exercises]

# -------------------------------------------
# *** Install Learners Environment ***
# -------------------------------------------

- include: learners.yml
  tags: [learners]

# -------------------------------------------
# *** Service ***
# -------------------------------------------

- include: systemd.yml
  tags: [systemd]

# -------------------------------------------
# *** nginx ***
# -------------------------------------------

- include: nginx.yml
  tags: [nginx]