---
- name: load default vars
  ansible.builtin.include_vars: learners.yml

- name: install learners
  ansible.builtin.include_tasks: learners.yml
  tags: [learners]

- name: configure exercises
  ansible.builtin.include_tasks: exercises.yml
  tags: [exercises]

- name: configure nginx
  ansible.builtin.include_tasks: nginx.yml
  tags: [nginx]
