---

# -------------------------------------------
# *** Disable unattended upgrades ***
# -------------------------------------------

- name: Disable timers for unattended upgrades
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - "apt-daily.timer"
    - "apt-daily-upgrade.timer"
  become: yes

- name: Reload systemctl daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Wait for running unattended upgrades to finish
  ansible.builtin.command: |
    systemd-run 
    --property="After=apt-daily.service apt-daily-upgrade.service" 
    --wait /bin/true
  become: yes

# -------------------------------------------
# *** Prerequisites ***
# -------------------------------------------

- name: "Set github Access Token"
  pause:
    prompt: "Please enter the github access token"
    echo: yes
  register: access_token
  when: |
    learners_exercises_git.private_repo | default(True)
    and not learners_exercises_git.keyfile is defined
    and not GIT_ACCESS_TOKEN

- name: "Register Access Token"
  set_fact:
    GIT_ACCESS_TOKEN: "{{ access_token.user_input  }}"
  when: access_token.user_input is defined

# -------------------------------------------
# *** Learners ***
# -------------------------------------------

- name: Deploy learners App
  ansible.builtin.include_role:
    name: "ansible-flask"
    vars_from: "/{{ role_path }}/vars/learners.yml"

# -------------------------------------------
# *** Venjix ***
# -------------------------------------------

- name: Deploy venjix
  ansible.builtin.include_role:
    name: "ansible-flask"
    vars_from: "/{{ role_path }}/vars/venjix.yml"

# -------------------------------------------
# *** Exercises ***
# -------------------------------------------

- include_tasks: exercises.yml
  tags: [exercises]

# -------------------------------------------
# *** Enable unattended upgrades ***
# -------------------------------------------

- name: Enable timers for unattended upgrades
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - "apt-daily.timer"
    - "apt-daily-upgrade.timer"
  become: yes

- name: Reload systemctl daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
