---
- name: "00 bootstrap"
  ansible.builtin.include_tasks: 00_bootstrap.yml

- name: "01 clone repo"
  ansible.builtin.include_tasks: 01_clone_repo.yml

- name: "02 install dependencies"
  ansible.builtin.include_tasks: 02_dependencies.yml

- name: "03 frontend"
  ansible.builtin.include_tasks: 03_frontend.yml

- name: "04 backend"
  ansible.builtin.include_tasks: 04_backend.yml

- name: "05 content"
  ansible.builtin.include_tasks: 05_content.yml

- name: "06 systemd"
  ansible.builtin.include_tasks: 06_systemd.yml

- name: "07 nginx"
  ansible.builtin.include_tasks: 07_nginx.yml
