---

# - name: Change IP-addresses
#   ansible.builtin.replace:
#     path: "{{ learners_exercises_paths.repo }}/\
#       themes/learners/static/js/learners_1.js"
#     regexp: (?<={{ item.key }} = )"(.*?)"
#     replace: "\"{{ item.value }}\""
#   loop: "{{ learners_ip_replacements | dict2items }}"
#   become: yes

# - debug:
#     msg: "{{ learners_components }}"

# - debug:
#     msg: "{{ breaker }}"

# -------------------------------------------
# *** Learners ***
# -------------------------------------------

- name: Deploy learners App
  ansible.builtin.include_role:
    name: "ansible-flask"
    vars_from: "/{{ role_path }}/vars/learners.yml"

# -------------------------------------------
# *** Venjix ***
# -------------------------------------------

- name: Deploy venjix
  ansible.builtin.include_role:
    name: "ansible-flask"
    vars_from: "/{{ role_path }}/vars/venjix.yml"

# -------------------------------------------
# *** Exercises ***
# -------------------------------------------

- include: exercises.yml
  tags: [exercises]