---
- name: Load default vars
  ansible.builtin.include_vars: learners.yml

- name: Check github pat
  ansible.builtin.debug:
      msg:
          GITHUB PAT ist unset please set `learners_github_pat` or set env
          `GITHUB_PAT`
  when: learners_github_pat == ""

# Bootstrap

- name: Ensure learners build packages are installed
  become: true
  ansible.builtin.package:
      name: '{{ learners_packages }}'
      state: present
      update_cache: true

- name: Create learners user
  become: true
  ansible.builtin.user:
      name: '{{ learners_user }}'
      home: '{{ learners_basepath }}'
      shell: /usr/sbin/nologin
      create_home: false

- name: Create {{ learners_basepath }}
  become: true
  ansible.builtin.file:
      path: '{{ learners_basepath }}'
      owner: '{{ learners_user }}'
      group: '{{ learners_user }}'
      mode: '0755'
      state: directory

- name: Copying service-template to server
  become: true
  ansible.builtin.template:
      src: templates/learners.service.j2
      dest: /etc/systemd/system/learners.service
      mode: preserve

- name: Install learners frontend
  ansible.builtin.include_tasks: learners_frontend.yml
  tags: [learners]

- name: Install learners backend
  ansible.builtin.include_tasks: learners_backend.yml
  tags: [learners]

- name: Configure exercises
  ansible.builtin.include_tasks: exercises.yml
  tags: [exercises]
  when: >
      ( learners_deploy.full | default(False) ) or (
      learners_deploy.documentation | default(False) ) or (
      learners_deploy.exercises | default(False) ) or (
      learners_deploy.presentations | default(False) )

- name: Configure nginx
  ansible.builtin.include_tasks: nginx.yml
  tags: [nginx]
