---


# -------------------------------------------
# *** Learners ***
# -------------------------------------------

- name: Deploy learners App
  ansible.builtin.include_role:
    name: "ansible-flask"
    vars_from: "/{{ role_path }}/vars/learners.yml"

# -------------------------------------------
# *** Venjix ***
# -------------------------------------------

- name: Deploy venjix
  ansible.builtin.include_role:
    name: "ansible-flask"
    vars_from: "/{{ role_path }}/vars/venjix.yml"

# -------------------------------------------
# *** Exercises ***
# -------------------------------------------

- include: exercises.yml
  tags: [exercises]