---

# -------------------------------------------
# *** nginx ***
# -------------------------------------------

- name: Ensure <{{ learners_nginx_packages | join(', ') }}> is installed
  ansible.builtin.package:
    name: "{{ learners_nginx_packages }}"
    state: latest
    update_cache: yes
  become: yes

- name: Remove default config
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: 
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/conf.d"
  become: yes
  notify: restart nginx
