---
- name: Remove default config
  ansible.builtin.file:
      path: '{{ item }}'
      state: absent
  loop:
      - /etc/nginx/sites-enabled/default
  become: true
  notify: Restart nginx

- name: Add NGINX configuration file
  ansible.builtin.template:
      src: nginx_learners.conf.j2
      dest: /etc/nginx/conf.d/learners.conf
      mode: '0644'
  become: true
  notify: Restart nginx
