---
- name: "render ansible_documentation_{{ item.name }}.yaml from hugo_params.yaml.j2"
  ansible.builtin.template:
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    src: templates/hugo_params.yaml.j2
    dest: "{{ learners_exercise_build_path }}/ansible_documentation_{{ item.name }}.yaml"
    mode: preserve
  become: true
  vars:
    publish_dir: "{{ learners_documentation_path }}/{{ item.name }}"
    base_url: "{{ learners_documentation_endpoint }}"

- name: "render ansible_exercises_{{ item.name }}.yaml from hugo_params.yaml.j2"
  ansible.builtin.template:
    owner: "{{ learners_user }}"
    group: "{{ learners_user }}"
    src: templates/hugo_params.yaml.j2
    dest: "{{ learners_exercise_build_path }}/ansible_exercises_{{ item.name }}.yaml"
    mode: preserve
  become: true
  vars:
    publish_dir: "{{ learners_exercises_path }}/{{ item.name }}"
    base_url: "{{ learners_exercises_endpoint }}"

- name: "Build static documentation with hugo"
  ansible.builtin.command:
    cmd: "hugo --config \
      {{ learners_exercise_build_path }}/base_config.yaml,\
      {{ learners_exercise_build_path }}/docu_config.yaml,\
      {{ learners_exercise_build_path }}/ansible_documentation_{{ item.name }}.yaml"
    chdir: "{{ learners_exercise_build_path }}"
    creates: "{{ learners_documentation_path }}/{{ item.name }}/index.html"
  become: true
  become_user: "{{ learners_user }}"

- name: "Build static exercises with hugo"
  ansible.builtin.command:
    cmd: "hugo --config \
      {{ learners_exercise_build_path }}/base_config.yaml,\
      {{ learners_exercise_build_path }}/exercises_config.yaml,\
      {{ learners_exercise_build_path }}/ansible_exercises_{{ item.name }}.yaml"
    chdir: "{{ learners_exercise_build_path }}"
    creates: "{{ learners_exercises_path }}/{{ item.name }}/index.html"
  become: true
  become_user: "{{ learners_user }}"
