---
- name: Start and enable learners
  become: true
  ansible.builtin.systemd:
    name: learners.service
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart learners
  become: true
  ansible.builtin.service:
    name: learners
    state: restarted

- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
