---
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: restart learners
  ansible.builtin.service:
    name: learners
    state: restarted
  become: true
