learners_config_jwt:
  jwt_secret_key: "{{ 42 | to_uuid }}"
  # jwt_for_vnc_access: True
  # jwt_access_token_duration: 720

learners_config_database:
  db_uri: "sqlite:///{{ learners_basepath }}/data.db"

# learners_config_learners:
#   theme: "dark"
#   language_code: "en"
#   upload_folder: "/var/tmp"
#   upload_extensions: ["txt", "pdf", "png", "jpg", "jpeg", "gif", "json", "svg"]

# learners_config_venjix:
#   auth_secret: ""
#   url: ""

# learners_config_callback:
#   endpoint: "/callback"

# learners_config_novnc:
#   server: ""

learners_config_statics:
  directory: "{{ learners_wwwroot }}"
  # serve_mode: "role"

# learners_config_staticsites:
#   - url: ""
#     id: ""
#     title: ""
#     icon: "icon_web"

learners_config_serve_documentation:  "{{ ( learners_deploy['full'] | default(False) ) or 
                                      ( learners_deploy['documentation'] | default(False) ) }}"
learners_config_serve_exercises:      "{{ ( learners_deploy['full'] | default(False) ) or 
                                      ( learners_deploy['exercises'] | default(False) ) }}"
learners_config_serve_presentations:  "{{ ( learners_deploy['full'] | default(False) ) or 
                                      ( learners_deploy['presentations'] | default(False) ) }}"

learners_config_exercise_json: "{{ learners_wwwroot }}/hugo/exercises.json"
learners_config_questionaire_json: "{{ learners_wwwroot }}/hugo/questionaires.json"
learners_config_questionaires_questions_json: "{{ learners_wwwroot }}/hugo/questionaires_questions.json"