---
learners_config_jwt:
  jwt_secret_key: "{{ 42 | to_uuid }}"

learners_config_database:
  db_uri: sqlite:///{{ learners_basepath }}/data.db

learners_config_statics:
  directory: "{{ learners_wwwroot }}"

learners_config_exercise_json: "{{ learners_wwwroot }}/hugo/exercises.json"
learners_config_questionaire_json: "{{ learners_wwwroot }}/hugo/questionaires.json"
learners_config_page_json: "{{ learners_wwwroot }}/hugo/pages.json"

learners_users:
  user1:
    password: user1
    vnc_clients:
      soc_client:
        target: placeholder_1
        tooltip: SOC client
        username: csirt1
        password: placeholder
      pps_client:
        target: placeholder_3
        tooltip: PPS client
        username: csirt3
        password: placeholder
  user2:
    password: user2
    vnc_clients:
      soc_client:
        target: placeholder_1
        tooltip: SOC client
        username: csirt1
        password: placeholder
      pps_client:
        target: placeholder_3
        tooltip: PPS client
        username: csirt3
        password: placeholder
